### PR TITLE
Styling admin

### PR DESCRIPTION
**Pull request by ainsleywagon**
Styling the admin page so it looks okay!

### CODE REVIEW

**Comment by ainsleywagon** [comment]
screen shot 2014-07-11 at 7 06 12 pm

**Comment by chrisrodz** [comment]
Looks awesome Ainsley!

Haven't reviewed the code, but I have a question judging from the screenshot:
Where would I go if I wanted to view all of the fields of an opportunity? without necessarily wanting to edit it

**Comment by ainsleywagon** [comment]
Hey! That's a good question.

There's a couple of options:
- We could have an option for expanding to view all the fields on that
  current page
- We could make the title of the program a link to a page that contains all
  the fields and that page can have an additional option to edit/delete.

On Sat, Jul 12, 2014 at 12:36 AM, Christian A. Rodriguez <
notifications@github.com> wrote:

> Looks awesome Ainsley!
> 
> Haven't reviewed the code, but I have a question judging from the
> screenshot:
> Where would I go if I wanted to view all of the fields of an opportunity?
> without necessarily wanting to edit it
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CoquiCoders/bizwallet/pull/26#issuecomment-48804970.

## 

Ainsley Wagoner | @ainsleywagon https://twitter.com/ainsleywagon
2014 Code for America Fellow
Team Puerto Rico | Follow our journey http://coquicoders.org/

**Comment by MrMaksimize** [comment]
So there's actually a mockup for this kind of thing:  http://biz-finance-123.webflow.com/incentive-example 

However, that should not live under admin.  That should have it's own separate path at something like opportunities/{id} and the title would link from admin there.  So basically what ainsley said.  Because that would be used for admin viewing as well as for business owner viewing

**Comment by MrMaksimize** [comment]
Looks good to me.  Merging this sucka :)  ++ Ainsley!

**Pull request merged**
