### PR TITLE
[Hold] Wizard email req based

### PR DESCRIPTION
**Pull request by MrMaksimize**
- [x] Hide Test Path
- [x] Release email sends
- [x] DeOptionize

http://take.ms/dFack

Holding until requirements are done because we can't abuse git like this.

http://localhost:3737/debug/email-template/sendlead-agency/render
tests email rendering
http://localhost:3737/debug/email-template/sendlead-agency/send
tests email sending

### CODE REVIEW

**Comment by ainsleywagon** [comment]
screen shot 2014-10-09 at 2 04 56 pm

**Comment by MrMaksimize** [comment]
oooh snap! go @ainsleywagon!!! are we good to go with this guy?

**Comment by MrMaksimize** [comment]
Lol tests are passing, but we're not testing the emails

**Comment by ainsleywagon** [comment]
@MrMaksimize oh testsss. wanna pair on that?
The other thing is - I actually wasn't able to preview sendlead/agency/send so we need to check that before merging.

**Pull request merged**
